services:
  db:
    image: postgres:16
    container_name: postgres-biblioteca
    restart: "no"
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: biblioteca_db
    ports:
      - "5432:5432"
    volumes:
      - pg_aula4_data:/var/lib/postgresql/data

volumes:
  pg_aula4_data:
